# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.4
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Pregxxy addon for Hex Casting
display_name: Pregxxy
github_repo: pregxxy
github_user: SoccyUwU
java_package: io.github.soccyuwu.pregxxy
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 0.1.0
modid: pregxxy
